### ISSUE TITLE
SQL_Callback Error (2450)

### ISSUE THREAD

**Issue by northeaster** [levelsranks/levels-ranks-core#24]
L 12/24/2019 - 16:02:27: [levelsranks.smx] SQL_Callback Error (2450): Incorrect string value: '\xF0\x9F\x93\x97^1...' for column `oyntch_ntX0JkS`.`lvl_base`.`name` at row 1

**Comment by mgeerse** [comment]
I have the same problem. It is caused by players having special characters in their name. A name such as `𝐌𝐎𝐑𝐆𝐀𝐃𝐎 `or `𝓼𝔁𝓵𝓽𝔂 `will cause this. 

The playername is gathered with the GetPlayerName() function from SourceMod in databases.sp on line 252 (in the SaveDataPlayer) function.

The name does get converted to `\xF0\x9F\x93\x97^1...` but it can't get updated/inserted into the database. So far I have not found a fix.

I have tried to change the column collation from `utf8_general_ci `to `utf8mb4_general_ci` without any luck

**Comment by Wend4r** [comment]
This problem is related to the incompatibility of your database with dbi.mysql sourcemod driver. The plugin has nothing to do with this. 
Write here with this problem - https://github.com/alliedmodders/sourcemod/issues .

**Comment by Wend4r** [comment]
Link to Link to https://github.com/alliedmodders/sourcemod/issues/1150
